### ISSUE TITLE
Edit Shortcut shortcut not working (cmd + .) 

### ISSUE THREAD

**Issue by lilshim** [klaussinani/tusk#101]
**Describe the bug**

Shortcut for opening Edit Shortcut Keys noops

**To Reproduce**
Steps to reproduce the behavior.

![image](https://user-images.githubusercontent.com/5432430/43090324-ee1189a2-8e5b-11e8-80ae-b9473be5cdc9.png)
Click Edit Shortcut Keys or attempt to use 'cmd + .' 

**Expected behavior**

json shortcut file should be open 

**Screenshots**

**Technical Info (please complete the following information)**
 - OS:
![image](https://user-images.githubusercontent.com/5432430/43090377-07bbb670-8e5c-11e8-99cf-e3d352a566af.png)

 - Tusk Version:0.11

**Additional context**

**Comment by klaussinani** [comment]
Try setting a text editor as the default app for opening `~/.tusk.json` or `JSON` files in general. Please feel free to reach out again if the issue persist.
