### ISSUE TITLE
Vibrant Theme DIsplay Issue

### ISSUE THREAD

**Issue by livejamie** [klaussinani/tusk#102]
I'm getting this weird display issue where the top seems to be missing on both the dark and light theme.

Is there a way to fix or is this a bug?

![image](https://user-images.githubusercontent.com/49513/43276442-8875b78e-90b9-11e8-95f4-6c08721d74b1.png)

**Comment by jananiravi** [comment]
I have the above issue only occasionally, but I have another related display issue with the Vibrant theme @klauscfhq 
![image](https://user-images.githubusercontent.com/8397074/43612744-4417fea4-967b-11e8-9d5b-0e745e903964.png)
Neither the note titles nor the dates are readable anymore! I love the theme. So, a fix would be great.

It is almost readable in the dark theme:
![image](https://user-images.githubusercontent.com/8397074/43612824-71b1f8ce-967b-11e8-98ca-639c0b806e08.png)
Some higher contrast colors would be helpful here too.

*Using Tusk for macOS (High Sierra), v0.11.0 w/ Evernote Plus subscription.*

Thanks!

**Comment by klaussinani** [comment]
Support for both vibrant themes has been permanently dropped https://github.com/klaussinani/tusk/commit/dbb6cf8d672aa2b3b449949c8f3146dc2c633f5c
