### ISSUE TITLE
Cannot type Japanese from Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ibayashi-hikaru** [klaussinani/tusk#105]
**Is your feature request related to a problem? Please describe.**
As written in title, Japanese cannot be used from Ubuntu 16.04 LTS. I'm not sure this happens on other environments. I'm using Japanese introduced here http://www.localizingjapan.com/blog/2017/08/20/japanese-input-on-ubuntu-16-04-lts-xenial-xerus/
I guess this is the most popular software.

**Comment by swordgreen** [comment]
The same to Chinese input.

**Comment by chengwengao** [comment]
Input Chinese is not supported,me too.

**Comment by chengwengao** [comment]
> Input Chinese is not supported,me too.

sorry,The answer is here:https://github.com/klauscfhq/tusk/issues/58

**Comment by klaussinani** [comment]
Please see https://github.com/klaussinani/tusk/issues/58.
