### ISSUE TITLE
FeatureRequest: Duplicate Note

### ISSUE THREAD

**Issue by achimwessling** [klaussinani/tusk#111]
The windows desktop app has a feature to duplicate a note to another notebook. This way it is possible to work with templates. Any possibilty to establish this behaviour in your client would be welcome!

**Describe the solution you'd like**
A shortcut and a dialogbox which asks for the notebook where to paste the duplicate would be enough. Maybe a menu-item would be fine for the guys who treat the mouse. ;-)

The dialog could be extended by extra possibilities like

- setting the new title 
- adding / removing tags

**Additional context**
I could provide a screenshot of the 'official client' as a starting point.

**Comment by sleidig** [comment]
The new Evernote Web seems to have integrated that already, when you open a note and go to the "..." menu it has the option "Duplicate note" now.

**Comment by achimwessling** [comment]
![bildschirmfoto von 2019-01-01 17-05-29](https://user-images.githubusercontent.com/833288/50574363-bfeb8300-0de7-11e9-859e-7af685d00b1d.png)
Sorry, but I do only have the option to copy the link of the note! Are there different web clients? Obviously I do use the german version of it.

**Comment by sleidig** [comment]
Oh, there actually are different versions now. The "new" version I was talking about is in Beta, see here: https://discussion.evernote.com/topic/113856-new-web-experience-beta-now-available/

**Comment by achimwessling** [comment]
Thanks! Sorry, I should have been more up to date!
