### ISSUE TITLE
Find within note

### ISSUE THREAD

**Issue by olantrust** [klaussinani/tusk#113]
It would be incredibly useful for a user to be able to search the current open note for a search term.

The user could access this by:

a) a button
b) a shortcut (for example CTRL+SHIFT+F)
c) a menu item

**Comment by vushe** [comment]
Waiting almost for years...
https://github.com/klauscfhq/tusk/issues/53

**Comment by tamkaho** [comment]
me too

**Comment by klaussinani** [comment]
Please follow https://github.com/klaussinani/tusk/issues/53 for updates.
