### ISSUE TITLE
Add the ability to disable Auto Update Check

### ISSUE THREAD

**Issue by srgnk** [klaussinani/tusk#134]
**Is your feature request related to a problem? Please describe.**
Add the option to disable Tusk Auto Update Check. 
Function autoUpdateCheck() checks the github page for new updates but I installed Tusk using Ubuntu snap and I am OK to keep it updating the same way. Showing the 'New Upgrade is Available' even once a day could be annoying.

**Describe the solution you'd like**
An additional 'Disable Auto Updates' option in 'Update Check Frequency' menu would probably work.
![image](https://user-images.githubusercontent.com/34791865/49211999-3ba97880-f3c1-11e8-89b3-d697c1ff85ac.png)

**Comment by nickallevato** [comment]
please, and thank you. I get this multiple times a day across devices, but thanks to the post above only now once a day.
Thanks for the great app.

**Comment by herobix** [comment]
I would love to see this
I don't mind getting once that a new update is coming
Sometimes I have to 2 notifications that appeared and it is just annoying. I am close to finding another evernote wrapper to use.

**Comment by Smidra** [comment]
Would you consider putting Tusk on Flathub? The snap version looks ugly on Fedora. I do not mind any updates presuming they would be nicely integrated into my system. :) Just an idea. 

Thank you.
