### ISSUE TITLE
Display PDF's inline

### ISSUE THREAD

**Issue by jorythompson** [klaussinani/tusk#136]
I read in a previous feature request that you said that the default behavior for Evernote was to display PDF attachments as an icon and that is why Tusk does so.
This is not the case any longer (I don't remember when it was.)
I extensively import PDF's into Evernote and am able to view them inline, directly in the right pane.
This is a very important feature for me as most of my 11,000 notes contain PDF's.  
This saves me having to download and open them or even click on the attachent:
![capture](https://user-images.githubusercontent.com/13970384/50103504-bf52ca00-01f5-11e9-98ba-350afa24bf68.PNG)

Note that even the PDF's are displayed in the middle preview column.  

If I am missing something that is covered in the manual, I apologize;  please point me to the relevant section.

**Comment by klaussinani** [comment]
Please follow #88 for updates.

**Comment by jorythompson** [comment]
I don't see the relevance.  #88 is talking about the dark theme.  I am asking about inline PDF files.
