### ISSUE TITLE
Keyboard shortcuts not working (Linux Mint 18.1)

### ISSUE THREAD

**Issue by mleiseca** [klaussinani/tusk#137]
**Describe the bug**
Using any keyboard shortcuts yields an error

**To Reproduce**
For example, Type Ctrl-N to create a new note. Nothing happens in the UI, but if you open the javascript console, you see the error:
Uncaught TypeError: Cannot read property 'click' of null
    at Nav.click (/snap/tusk/18/resources/app.asar/src/nav.js:45)
    at EventEmitter.ipc.on (/snap/tusk/18/resources/app.asar/src/browser.js:158)
    at EventEmitter.emit (events.js:182)

Using any other keyboard shortcut follows the same pattern.

**Expected behavior**
A note should be created.

**Technical Info (please complete the following information)**
 - OS: Linux Mint 18.1
 - Tusk Version: 0.12.0
Other version info:
Electron: 3.0.12
Chrome: 66.0.3359.181
Node: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.4.0-53-generic

**Additional context**

**Comment by mleiseca** [comment]
It looks like there are a number of issues if you use 'new Evernote web'. I downgraded to the old Evernote web and things work properly.

**Comment by klaussinani** [comment]
Please follow #88 for updates.
