### ISSUE TITLE
Themes not working (Win 10)

### ISSUE THREAD

**Issue by MikePSO** [klaussinani/tusk#145]
**Describe the bug**
When selecting a theme nothing changes. Neither with Automode nor manual selection of a darker theme. Tested on multiple Win 10 computers

**To Reproduce**
Select a different theme

**Expected behavior**
Theme should change

**Technical Info (please complete the following information)**
 - OS: Win 10
 - Tusk Version: 17

**Comment by enoversum** [comment]
The same here, just installed and wanted to try out. Also, Ctrl + K or choosing Focus Mode manually via the menu doesn't work either.

**Comment by Prestoo** [comment]
Same here. It doesn't work manully or the shortcut way neither

**Comment by klaussinani** [comment]
Please see #88 for more info
