### ISSUE TITLE
0.17.0 deb install fails

### ISSUE THREAD

**Issue by Amandaville** [klaussinani/tusk#147]
**Describe the bug**
Failed to install package 'tusk_0.17.0_amd64.deb'

**To Reproduce**
Tried twice, failed both times

**Expected behavior**
I expect it to install like every version before it

**Screenshots**

![screenshot from 2019-01-10 10-37-43](https://user-images.githubusercontent.com/37563017/50944843-ad96d680-14c4-11e9-9508-417572541e2e.png)

**Technical Info (please complete the following information)**
 - OS: Linux Mint 18.3
 - Tusk Version: 0.17.0

**Additional context**

**Comment by Amandaville** [comment]
tusk_0.18.0_amd64.deb fails also.  I guess I'm stuck on tusk_0.11.0 until this is resolved.

**Comment by RyanNerd** [comment]
@Amandaville I was able to get `tusk_0.21.0_amd64.deb` to install and work on Linux Mint 19.
Hopefully it will work in LM18 as well.

**Comment by Amandaville** [comment]
Still failing for me with tusk_0.21.0_amd64.deb

![2019-01-22_08-53](https://user-images.githubusercontent.com/37563017/51507425-76f58000-1e23-11e9-9b28-1819a1bc8aaf.png)

**Comment by RyanNerd** [comment]
@Amandaville That's unfortunate. No error message? Just hangs at 95%?

Try executing these commands and then try installing again:

```
sudo apt clean
sudo apt autoclean
```
Failing that you can try manually downloading the deb file and execute it in the terminal and see if you get any error message feedback you can share here. HTH

**Comment by Amandaville** [comment]
@RyanNerd I had previously attempted installing by opening the .deb file in nemo. 

I just tried it from the command line with `sudo dpkg -i tusk_0.21.0_amd64.deb --log=tusk.log`

I did not include --force as I do not understand what that does exactly.  There are references in the manual to --force-depends, --force-all, --force-architecture, and other --force-(commands) but without understanding --force, I am hesitant to use it.   

This was the result in the terminal as the log file failed to be created.


> $ sudo dpkg -i tusk_0.21.0_amd64.deb --log=tusk.log
(Reading database ... 257794 files and directories currently installed.)
Preparing to unpack tusk_0.21.0_amd64.deb ...
Unpacking tusk (0.21.0-622) ...
dpkg: error processing archive tusk_0.21.0_amd64.deb (--install):
 trying to overwrite '/opt/Tusk/content_shell.pak', which is also in package tusk-app 0.11.0-472
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
dpkg: error processing archive --log=tusk.log (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 tusk_0.21.0_amd64.deb
 --log=tusk.log

**Comment by Amandaville** [comment]
@klaussinani 
> For debian based distros, the `snap` package is a better installation option compared to the `deb` one, since it includes automatic updates by default, through the `snap` package manager. For more info please see https://snapcraft.io/tusk.

I tried the Appimage on an earlier version because of a similar recommendation and lost a half day of work trying to figure out why I couldn't add images to my notes.  There was no warning that images can only be added from the default /home directory and all of my images are on an attached usb hard drive.  It is apparently a limitation or security feature of Appimage.

Is there a similar limitation with Snap packages?  If so, it will not work for me.

**Comment by RyanNerd** [comment]
@Amandaville Thanks for trying my suggestion. There's now an error log that may help solve the problem. From the log it appears the previous version of Tusk has files that the installer does not want to overwrite.

@klaussinani makes the suggestion to completely purge the previous version. I believe this will solve the problem and the `--force` switch (had you chosen to use it) may have done this for you as it forces the version you are installing over any existing versions and tries to fix any dependencies.

I'm not sure if the version of Tusk via Snap is the same version as is in the `.deb` file -- if the annoying _security feature_ is part of Tusk in either version then the work around is to move images you want to copy into the your local drive in off the `/home/username/Pictures` directory perhaps???

**Note:** Just so you know -- I am not a developer that works on Tusk, but am a software developer familiar with how Linux works and I offered assistance that perhaps will help the actual Tusk team to solve this issue.

**Comment by Amandaville** [comment]
@RyanNerd Thanks for all the help.  I purged the previous Tusk installation and the .deb file installed with no errors.  Thanks for the explanation about the --force switch.  I will keep that in my toolbox for the next time I have a similar issue.  I appreciate your suggestion to move my images to my /home directory but I have nearly 2TB of images and a /home directory with less than 100MB of space left on the SSD, so that's not an option.  I'm good now that the .deb install completed, but I'm still curious if the Appimage has the same security limitations and @klaussinani hasn't replied yet.  Aside from that inquiry, this issue can be closed.

**Comment by klaussinani** [comment]
Unfortunately, that is true for Snapcraft as well. Due to the snap's strictly confined nature, read & write operations on files outside of the user's the generic $HOME variable are not possible. 
More info, about Snapcraft's architecture regarding package confinements & environment, is available on the official docs:

- [Snap Confinement](https://docs.snapcraft.io/snap-confinement/6233)
- [Environment Variables](https://docs.snapcraft.io/environment-variables/7983)

**Comment by Amandaville** [comment]
> Unfortunately, that is true for Snapcraft as well. Due to the snap's strictly confined nature, read & write operations on files outside of the user's the generic $HOME variable are not possible.
> More info, about Snapcraft's architecture regarding package confinements & environment variables, is available on the official docs:
> 
>     * [Snap Confinement](https://docs.snapcraft.io/snap-confinement/6233)
> 
>     * [Environment Variables](https://docs.snapcraft.io/environment-variables/7983)

Thank you for the reply, it saves me a lot of time.  Since my workflow requires access to directories outside of $HOME, I will stick with the .deb install.
