### ISSUE TITLE
Only show whitescreen when launch Tusk

### ISSUE THREAD

**Issue by morganchenjp** [klaussinani/tusk#150]
**Describe the bug**
After upgrade to v0.18, can only show white screen
Previously I use v0.14 or 0.15(can't remember it clearly), and Tusk worked very good. 
But after did an upgraded, then Tusk only show whitescreen.
Today, tried to uninstall old version, then reinstall newest v0.18, but still have same problem. 
Already deleted ".tusk.json" in my home folder. 

**To Reproduce**
Maybe a special problem on my machine. 
I am using Ubuntu-based Linuxmint distribution, kernel is 4.15.0-39-generic. 

**Expected behavior**
Show Tusk normal main screen.

**Screenshots**
![tusk-whitescreen-2019-01-16-13 06](https://user-images.githubusercontent.com/16369508/51227786-d1f52600-1990-11e9-8192-ba36cb906318.png)

**Technical Info (please complete the following information)**
 - OS: Ubuntu-based Linuxmint distribution. 
 - Tusk Version:v0.18 

**Additional context**

**Comment by morganchenjp** [comment]
Also tried to click "Log Out" from File menu, but nothing happened. 
Click "Evernote Setting" can launch browser and navigate to Evernote website. 

I am using International Evernote.

**Comment by klaussinani** [comment]
Try using the `View` > `Reload` option, to force-reload the app, since it looks a lot like a connectivity issue.
Please feel free to reach out again if the issue persist.

**Comment by morganchenjp** [comment]
Tried View ==> Reload several times, nothing changed, still white screen. 
Using File ==> Evernote Settings, can launch Firefox and show evernote official website. 

Both Linux Network and Firefox already configured proxy. 
Is there any special configuration for Tusk to configure proxy ? 
@klaussinani

**Comment by morganchenjp** [comment]
Did two things , then Tusk and work normally now. 
1. Changed Proxy configuration from automatic to Manual, 
2. Uninstall old version completely , then install new v0.21

![tusk-proxy-screenshot from 2019-02-11 10-24-28](https://user-images.githubusercontent.com/16369508/52546558-5c4b7100-2dfb-11e9-8bb1-ae892fc104f4.png)
![tusk-proxy-screenshot from 2019-02-11 10-25-34](https://user-images.githubusercontent.com/16369508/52546559-5fdef800-2dfb-11e9-87aa-ba9cd5abe325.png)

**Comment by hip23** [comment]
Hello. I have same bug.

_System:
Kernel: 4.15.0-76-generic x86_64 bits: 64  
Desktop: Cinnamon 4.4.8 
Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic_ 

i can see only white screen same as user morganchenjp mentioned before

_about tusk 0.23.0 (x64): 
Version: 0.23.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-76-generic_

View > Reload doesnt help

**Comment by morganchenjp** [comment]
Right now using 0.23, don't have this issue.

**Comment by bharat76** [comment]
Same issue still. White screen and does not process further. 
Tusk 0.23.0 (X64)
Kernel : 5.3.0-26-generic #28~18.04.1-Ubuntu

**Comment by nicegeeker** [comment]
Same issue still. White screen and does not process further.
Tusk 0.23.0

**Comment by bradrf** [comment]
If it's at all helpful, when I open the DevTools and reload, I see this: 
![image](https://user-images.githubusercontent.com/295715/107674581-f42f0000-6c4b-11eb-9750-256c3b0e2578.png)

**Comment by alejandra-jamilis** [comment]
Hi, I'm experimenting the same issue on Ubuntu 18, Tusk 0.23

![image](https://user-images.githubusercontent.com/76124996/107683655-95d04480-6c80-11eb-9526-2b4696790526.png)

This happens after successful login

**Comment by mathias4833** [comment]
+1, I have the same issue

**Comment by abrindha** [comment]
I have been seeing the same issue for 2 days now. Using version 0.23.

**Comment by mordaga** [comment]
+1, same issue...
tusk_0.23.0_amd64
Pop OS 20.04

**Comment by akvilonBrown** [comment]
+1 

Version: 0.23.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic

**Comment by fonylew** [comment]
+1 I have the same issue a couple of days ago.

Tusk 0.23.0 (x64)
Version: 0.23.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.8.0-43-generic

**Comment by SachinA2P** [comment]
+1

**Comment by maivincent** [comment]
+ 1, happened to me too. Can login through Google and then it is a white screen.

Version: 0.23.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.4.0-65-generic

**Comment by rklak** [comment]
This issue needs to be reopen

**Comment by cristim13** [comment]
It seems everytime Evernote makes an upgrade, Tusk needs to do it as well, otherwise it gets stuck. I am facing the same issue with the white screen after credentials are given to log in.
Tusk version: 0.23.0
Electron version: 4.2.2

**Comment by fonylew** [comment]
Hi,
I found that this PR has solved the issue. https://github.com/klaussinani/tusk/pull/317 You can either checkout that forked branch, since it has not been merged at the moment. Or you can follow this to solve your problem as well https://github.com/klaussinani/tusk/issues/308#issuecomment-777084435
