### ISSUE TITLE
Wrong date with insert date(-time) stamp

### ISSUE THREAD

**Issue by unexpected-error** [klaussinani/tusk#151]
When using insert date(-time) stamp, I get a wrong (and impossible) date.
On Jan 16 2019 I get 
0/3/2019 (with date stamp) and
0/3/2019 21:58:1  (with date-time step).

Let me know if I can provide further information.

Tusk 0.18.0 (x64) on Linux Mint 18.3

**Comment by klaussinani** [comment]
Thank you for taking the time to report the issue!
