### ISSUE TITLE
alt+tab showm menu

### ISSUE THREAD

**Issue by emoxam** [klaussinani/tusk#152]
**Describe the bug**
When i try to switch the keyboard layout with alt+shit tusk shows me menu instead of switching keyboard layout.

**To Reproduce**
At the some note press alt+shift to switch the keyboard layout

**Expected behavior**
Pressing alt+shift must switch the keyboard layout

**Screenshots**

**Technical Info (please complete the following information)**
 - OS: Linux mint cinnamon 19.1
 - Tusk Version: 0.19.0

**Comment by emoxam** [comment]
Enable global shortcuts keys is turned off, but atl+tab is showning menu anyway. Are you sure the problem is in global shortcuts?

**Comment by romkaspb** [comment]
Same bug in XFCE. It's very popular bug in electron apps, for example:
https://github.com/meetfranz/franz/issues/1088
https://github.com/zulip/zulip-electron/issues/528
https://github.com/RocketChat/Rocket.Chat.Electron/issues/50
https://github.com/vector-im/riot-web/issues/4345

And there is a very easy to fix:
https://github.com/meetfranz/franz/pull/1323

@klaussinani I can submit a PR, if you want.

**Comment by romkaspb** [comment]
Btw @emoxam saying about `alt+tab` at the topic of issue, and about `alt+shift` at it's body.
@emoxam, what is correct keys combination to reproduce your bug?
