### ISSUE TITLE
Daily Update notifications can't be switched off

### ISSUE THREAD

**Issue by piedrok** [klaussinani/tusk#156]
**Describe the bug**
After changing the update check frequency to daily, I still get a daily update check and a notification about it.

**To Reproduce**
Update checks cannot be switched off, even on repository based distributions. 

**Expected behavior**
Well that's easy: Just add a "Never" option to the setting "Update frequency". 

- First: I do not want my system to connect to an external site once a day to check for newer versions. 
- Second: Even in the middle of watching a movie or other acitivities durng which I do not want to be distracted, suddenly the Tusk update notification pops up! 
- Third: On a system working with repository based package management, update notifications do not make any sense nor will they ever be used (won't work even)... 

I am looking for a working note taking apllication. Tusk seems to be a solution on first glance but little things like this are just discouraging. Also I do not see what is gained by not having the option to turn off update checks completely. It is a nuisance which stems from the windows world wehre every application brings it's own background service. on linux we do not need that and as mentioned before, it douesn't make any sense in the majority of cases. 

Thx, with best regards, 
p.

**Comment by klaussinani** [comment]
Fixed on https://github.com/klaussinani/tusk/commit/d74c2430069a58645f8e67f94bf84cb6316b0623.
