### ISSUE TITLE
Theme toggle don't work on OSX

### ISSUE THREAD

**Issue by jadupl2** [klaussinani/tusk#164]
**Describe the bug**
Theme toggle don't work on OSX.
Views, Toggle theme, what ever theme you choose nothing change,

**To Reproduce**
Views, Toggle theme

**Expected behavior**
Suppose to see the theme color to change

**Technical Info (please complete the following information)**
 - OS: High SIerra 10.13.6
 - Tusk Version: 0.21.0.622

**Comment by klaussinani** [comment]
Please see #88 for more info

**Comment by livejamie** [comment]
It seems to occur no matter which version of Evernote is being used.

**Comment by novdddd** [comment]
@livejamie  Works fine on regular Evernote version

**Comment by klaussinani** [comment]
Duplicate of #88
