### ISSUE TITLE
No dark mode on Windows 10 1803

### ISSUE THREAD

**Issue by serjanbiogenic** [klaussinani/tusk#168]
**Describe the bug**
None of the toggle theme options work 

**Technical Info (please complete the following information)**
 - OS: Windows 10 1803
 - Tusk Version: 0.22

**Comment by PohaoGit** [comment]
I hope tusk supports evernote's new UI asap.

**Comment by novdddd** [comment]
if y wanting it so mach why not start contributing 😜

**Comment by minasm** [comment]
The same issue goes for Ubuntu 18.04. Using Tusk 0.22.0 (x64).
Still loving it though:)

**Comment by AndreasPuhl** [comment]
Also true for Ubuntu 18.10

**Comment by novdddd** [comment]
https://github.com/klaussinani/tusk/issues/88
@AndreasPuhl  @minasm Search befor openning issues 😜

**Comment by klaussinani** [comment]
Please see #88 for more info
