### ISSUE TITLE
Strikethrough shortcut doesn't work

### ISSUE THREAD

**Issue by FifthRooter** [klaussinani/tusk#196]
**Describe the bug**
When I try use the Strikethrough shortcut using the keyboard combination, it doesn't work.

**To Reproduce**
Press Ctrl+T after text to be strikethroughed has been selected.

**Expected behavior**
The selected text should have a line running across the middle of it (a strikethrough).

**Technical Info (please complete the following information)**
 - OS: Ubuntu 18.04.2 (Gnome 3.28.2)
 - Tusk Version: 0.23.0

**Comment by zztalker** [comment]
Works fine for me, the selected text was strikethroughed after pressing Ctrl+T. 
OS: Linuxmint 19.1 (Cinnamon 4.0.10) same version of the Tusk.

**Comment by FifthRooter** [comment]
Shortcuts working now, thank you team! :))
