### ISSUE TITLE
Keyboard shortcuts & themes not working (Windows 10)

### ISSUE THREAD

**Issue by hariiprasath** [klaussinani/tusk#201]
No keyboard shortcuts (except text formatting ones) are working. Cannot open 'Edit Keyboard Shortcuts' from the menu as well. 'Enable Global Shortcut Keys' does not change anything.

Also, toggling theme in View menu only changes the colour of the scrollbar and nothing else.

**Comment by novdddd** [comment]
Hope helps #88

**Comment by hariiprasath** [comment]
> Hope helps #88

Thank you. I apologise for creating a new issue without proper research. Looks like I was using the new Evernote Web. Everything worked fine once I switched back to the old version.

But is Tusk for the new Evernote Web coming out anytime soon?

**Comment by novdddd** [comment]
It appears no  - but we can help and support @klaussinani to work more on the new Evernote version by recommemding him to GitHub Sponsors https://forms.gle/6zoiq8jdagoMm9N48 🚀

**Comment by AhmadShiddiq** [comment]
> Hope helps #88

thanks :D, you save me.

**Comment by ei8fdb** [comment]
Same as #258 and edit shortcuts #241

**Comment by ei8fdb** [comment]
The (current) answer to the "shortcut keys not working" issue is to use the original Evernote interface, as documented in #88, [specifically here](https://github.com/klaussinani/tusk/issues/88#issuecomment-397377296).

I've done this and confirmed I can now use shortcuts (ctrl+shirt+l = add link)

**Comment by MostHated** [comment]
Based on the looks of it, the themes are just not working right currently? I switched back to the original instead of new, but as someone else in there posted in their pic, the majority of the UI is white when toggling dark mode. It was a month or so since that was last updated but I am guessing that particular issue is still pending?

**Comment by KeiraX** [comment]
Same Problem with me.
