### ISSUE TITLE
Paste as "Plain Text"

### ISSUE THREAD

**Issue by d-walsh** [klaussinani/tusk#207]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Currently when I paste text into Tusk it always retains the original formatting. This is very annoying as I always I want the new text to have the format of the Tusk text. My current workaround is first I paste the text into NotePad and then copy from NotePad into Tusk.

**Describe the solution you'd like**

I would like Tusk to have an option in the Right Click menu to "Paste Text" and remove all copied formatting. A lot of other editors have this feature so it should be clear to understand.

So the options in the right click menu would be something like:
- Cut
- Copy
- Paste
- Paste Text

**Additional context**

**Comment by Amandaville** [comment]
I always use Ctrl+Shift+v to paste text without formatting.

**Comment by d-walsh** [comment]
@Amandaville Thanks!
