### ISSUE TITLE
Icon doesent show up in Ubuntu 19.10 and login problem

### ISSUE THREAD

**Issue by crydotsnake** [klaussinani/tusk#234]
Hello!, as the title says i cant see the icon of the app in my dock in ubuntu 19.10. But the tray icon works great!.

![tusk](https://user-images.githubusercontent.com/39345336/67636479-533ef900-f8d1-11e9-8b8c-5730eed19d19.png)

And everytime i started my PC i have to enter my account details to login.

Thank you btw for this amazing project! :).

**Comment by mbbroberg** [comment]
I have a similar icon in Fedora 30. I'm curious if there's something worth overriding in `/usr/bin/applications/tusk.desktop`, which points to `Icon=tusk`. I'm new, so not sure where it loads from, but  maybe that can get us both started on finding a solution @crydotsnake :smile:

**Comment by crydotsnake** [comment]
@mbbroberg I have the same.

**Comment by crydotsnake** [comment]
But i cant find any folder called tusk.

**Comment by mbbroberg** [comment]
I don't believe it's a folder called tusk, I believe it's a file in the /usr/share/icons/ folder. For instance, I find that the tusk.png file (which is 1024x1024) is showing up in the 0x0 folder only: 

```
├── hicolor
│   ├── 0x0
│   │   └── apps
│   │       └── tusk.png
```

While Firefox, for example, has icons in almost every subdirectory under `hicolor/`. 

I bet something went wrong with the icon propagation during the build. I hope that gets something started.

**Comment by crydotsnake** [comment]
Yep. I have the same. Maybe the path to the icon is not in the source code?. I'm searching already, because the icon has also be in the repository but i dont know the folder structure there.

**Comment by crydotsnake** [comment]
I think its in the `static` folder.

**Comment by crydotsnake** [comment]
Maybe it has something to do with this guy right here?: ``icon: is.linux && file.icon,`` in `src/win.js` line 42. I'm reallly not sure.

**Comment by mbbroberg** [comment]
@crydotsnake I fixed it on Fedora! By: 

- `git clone https://github.com/klaussinani/tusk && cd tusk`
- `cd docs/`
- `sudo cp favicon-16x16.png /usr/share/icons/hicolor/16x16/tusk.png`
- `sudo cp favicon-32x32.png /usr/share/icons/hicolor/32x32/apps/tusk.png`
- `sudo cp favicon-96x96.png /usr/share/icons/hicolor/96x96/apps/tusk.png`

After running `gsettings` to load a new theme, I now I have the icons showing on alt+tab and in the dock! 

![Screenshot from 2019-10-28 10-15-42](https://user-images.githubusercontent.com/1744971/67691049-f2183380-f96b-11e9-9867-db89d71500df.png)

**Comment by crydotsnake** [comment]
Nice!.
