### ISSUE TITLE
Tusk White Screen Issue 

### ISSUE THREAD

**Issue by Ppathak91** [klaussinani/tusk#261]
Since updating to version 0.23.0, upon launching Tusk, all its shows is a blank white screen. I'm running Tusk on OpenSuse Tumbleweed and already tried reloading and logging out but nothing works. I'd be grateful if someone could help me out. Thanks!

**Comment by hainguyen15** [comment]
Ị had the same issue yesterday but it's gone for now

**Comment by hainguyen15** [comment]
by the way, duplicate #255

**Comment by Ppathak91** [comment]
Yup its working fine now.
