### ISSUE TITLE
Whitescreen after sign in

### ISSUE THREAD

**Issue by chikihiri** [klaussinani/tusk#315]
I have a problem with tusk on linux. I always get whitescreen when i sign in. I tried to install again but i still have the same problem.

![Zrzut ekranu z 2021-02-10 21-39-08](https://user-images.githubusercontent.com/78867326/107569457-9e753c00-6be8-11eb-8d0d-318d5c36e746.png)

OS: Mint
Version: 20.1
Architecture: x86_64
Package Version: 0.23.0

**Comment by ivanfr90** [comment]
I'm suffering the same problem.

Details of my installation:

OS: Kubuntu
Version: 20.10
Architecture: x86_x64
Package Version: 0.23.0
Package: [tusk_0.23.0_amd64.deb](https://github.com/klaussinani/tusk/releases/download/v0.23.0/tusk_0.23.0_amd64.deb)

**Comment by gringochuck** [comment]
I'm experiencing the same issue. Installed via the snap store. Same issue. Removed program via snap command. Deleted all traces of tusk on OS. Installed via tusk-0.23.0-x86_64.AppImage, still same issue. 



OS: Ubuntu 20.04.2 LTS x86_64
Kernel: 5.8.0-43-generic
Version: 0.232.0

**Comment by GregDuhamel** [comment]
Same Here. May be related to Evernote last update.

**Comment by casojcode** [comment]
It works with this solution: 
https://github.com/klaussinani/tusk/issues/308

**Comment by chikihiri** [comment]
> I have a problem with tusk on linux. I always get whitescreen when i sign in. I tried to install again but i still have the same problem.
> 
> ![Zrzut ekranu z 2021-02-10 21-39-08](https://user-images.githubusercontent.com/78867326/107569457-9e753c00-6be8-11eb-8d0d-318d5c36e746.png)
> 
> OS: Mint
> Version: 20.1
> Architecture: x86_64
> Package Version: 0.23.0
