### ISSUE TITLE
Feature request: searchbox like in Chrome by `Ctrl + F`

### ISSUE THREAD

**Issue by vushe** [klaussinani/tusk#53]
First, thanks for the app!

What I'd suggest is to add search box as we have in Chromium by pressing `Ctrl+F`. The main advantage over the web search is that it allows quick searching within a note and quick jumping to the searched items. As this is an Electron-based app, I guess issue should not be hard to implement?

![image](https://user-images.githubusercontent.com/15868217/37755312-ad9580cc-2dad-11e8-9ba1-4c065397a61d.png)

**Comment by olantrust** [comment]
Is this relevant:
https://stackoverflow.com/questions/40987229/how-do-i-search-text-in-a-single-page-reactjs-electron-application

**Comment by olantrust** [comment]
https://github.com/TheoXiong/electron-find

**Comment by timoc** [comment]
Maybe allow a separate existing editor as a basis, like codemirror or TinyMCE, so you do not have to focus as much on making an IDE, but conversion to EML?

**Comment by e-stonia** [comment]
Can't search in the note at all? For real?

**Comment by vushe** [comment]
Well everyone is free to offer his own solution: this is GitHub in the end.

But regarding the time this particular issue is in `progress` and taking into account the amount of requests... I don't see any advantage of this product except it runs Evernote's web version in a separate application window within Electon JS (which isn't a huge deal as everyone can run practically any web page in Electron). 

So, here is solution: **FORGET THIS, USE EVERNOTE IN YOUR BROWSER**.

**Comment by novdddd** [comment]
you cant possibly expect @klaussinani to do everything, things take time in open source and without contributions from other users and programmers it is even harder to keep up, just look at the numder of pull Requests tusk has had over the years https://github.com/klaussinani/tusk/pulls , the comunity support is extremly low, just saying this peacefully 🕊

**Comment by vushe** [comment]
With all my respect, it's somewhat impolite to community to mark issue progressed if it actually isn't.
