### ISSUE TITLE
code block function doesn't work

### ISSUE THREAD

**Issue by mountain-geek** [klaussinani/tusk#95]
Hello, 
I'm trying to type in some code inside on the notes and
code block(format) doesn't seem to function since I click it on the menu bar or using ctrl+shift+l

Thank you

**Comment by noamteyssier** [comment]
Same here, Ubuntu 18.04

**Comment by nevgin** [comment]
Same here, Ubuntu 18.04

**Comment by melihbildik** [comment]
Same here, Mint 18

**Comment by Tomasz-Kluczkowski** [comment]
And me , ubuntu 18.04

**Comment by batjko** [comment]
Duplicate of #74

**Comment by jetacpp** [comment]
Same here, is this Evernote issue or Tusk issue ?

**Comment by Chadwiki** [comment]
Tusk 0.11.0 (x64) on Ubuntu 16.04

**Comment by klaussinani** [comment]
Please follow https://github.com/klaussinani/tusk/issues/74 for updates.
